---
debug: true

config:
  name: config-server

server:
  port: 8888

ribbon:
  eureka:
    enabled: true

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tw-leansw/leansw-config-docker

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
